description="Изменить написаный мной текст"
prompt = """
Вонтексте всего файла внеси изменения для выделенного текста

Это подробный сценарий для закадрового голоса видеоурока, следуя этим правилам:

1. Полная сохранность идей (Самое важное правило): Не удаляй, не сокращай и не упускай ни одной мысли или детали из исходного текста. Каждую мысль или предложение, даже если она кажется незначительной, нужно сохранить в том или ином виде. Твоя задача — не заменить, а взять каждую исходную мысль, перефразировать ее для лучшего понимания и значительно расширить, делая ее максимально понятной для новичка.

2. Целевая аудитория — новички: Всегда считай, что слушатель видит эту тему впервые. Используй очень подробные объяснения и аналогии из реальной жизни.

3. Стиль — разговорный и дружелюбный: Пиши текст так, как будто ты — терпеливый наставник, который ведет живой урок. Обращайся к зрителю напрямую ("вы", "давайте посмотрим", "представьте себе").

4. Форматирование — Markdown: Структурируй итоговый текст с помощью заголовков и подзаголовков для лучшей читаемости. Формат представления клавиш на клавиатуре не менять а оставить, например не Alt а ++alt++ это формат pymdownx. Выведи в чистом маркдаун и сразу примени к документу. Когда создаешь списки после * или после цифры напрмер 1. вставляй только один пробел.
"""